export const LINK_COMPANY = 'LINK_COMPANY';
export const UNLINK_COMPANY = 'UNLINK_COMPANY';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
